import type { RawPR } from '../types.js';

const hoursBetween = (a: string, b: string): number => {
  const ms = new Date(b).getTime() - new Date(a).getTime();
  return Math.round((ms / 3_600_000) * 10) / 10;
};

const pr = (
  override: Partial<RawPR> & Pick<RawPR, 'number' | 'createdAt' | 'mergedAt'>,
): RawPR => {
  const additions = override.additions ?? 50;
  const deletions = override.deletions ?? 10;
  return {
    title: `PR #${override.number}`,
    author: 'alice',
    timeToMergeHours: hoursBetween(override.createdAt, override.mergedAt),
    additions,
    deletions,
    totalLinesChanged: additions + deletions,
    changedFiles: 3,
    reviewComments: 2,
    totalComments: 3,
    reviewers: ['bob'],
    labels: [],
    ...override,
  };
};

export const SAMPLE_PRS: RawPR[] = [
  pr({
    number: 1,
    title: 'Baseline: tiny config tweak',
    author: 'alice',
    createdAt: '2026-03-29T09:00:00Z',
    mergedAt: '2026-03-29T11:30:00Z',
    additions: 4,
    deletions: 1,
    changedFiles: 1,
    reviewComments: 0,
    totalComments: 0,
    reviewers: [],
    labels: ['chore'],
  }),
  pr({
    number: 2,
    title: 'Baseline: long-running feature',
    author: 'bob',
    createdAt: '2026-03-30T08:00:00Z',
    mergedAt: '2026-04-02T08:00:00Z',
    additions: 820,
    deletions: 140,
    changedFiles: 18,
    reviewComments: 12,
    totalComments: 18,
    reviewers: ['alice', 'carol'],
    labels: ['feature'],
  }),
  pr({
    number: 3,
    title: 'Baseline: bugfix',
    author: 'carol',
    createdAt: '2026-04-01T12:00:00Z',
    mergedAt: '2026-04-01T18:30:00Z',
    additions: 22,
    deletions: 8,
    changedFiles: 2,
    reviewComments: 1,
    totalComments: 2,
    reviewers: ['alice'],
    labels: ['bug'],
  }),
  pr({
    number: 4,
    title: 'Baseline: large refactor',
    author: 'dave',
    createdAt: '2026-04-03T10:00:00Z',
    mergedAt: '2026-04-04T16:00:00Z',
    additions: 1450,
    deletions: 980,
    changedFiles: 42,
    reviewComments: 9,
    totalComments: 14,
    reviewers: ['alice', 'bob'],
    labels: ['refactor'],
  }),
  pr({
    number: 5,
    title: 'Baseline: docs update',
    author: 'alice',
    createdAt: '2026-04-05T09:30:00Z',
    mergedAt: '2026-04-05T10:15:00Z',
    additions: 18,
    deletions: 4,
    changedFiles: 1,
    reviewComments: 0,
    totalComments: 1,
    reviewers: [],
    labels: ['docs'],
  }),
  pr({
    number: 6,
    title: 'Baseline: dependency bump',
    author: 'bob',
    createdAt: '2026-04-08T14:00:00Z',
    mergedAt: '2026-04-09T09:00:00Z',
    additions: 60,
    deletions: 60,
    changedFiles: 4,
    reviewComments: 2,
    totalComments: 3,
    reviewers: ['carol'],
    labels: ['deps'],
  }),
  pr({
    number: 7,
    title: 'Comparison: same-day merge',
    author: 'alice',
    createdAt: '2026-04-12T09:00:00Z',
    mergedAt: '2026-04-12T11:00:00Z',
    additions: 35,
    deletions: 12,
    changedFiles: 3,
    reviewComments: 1,
    totalComments: 1,
    reviewers: ['bob'],
    labels: ['feature'],
  }),
  pr({
    number: 8,
    title: 'Comparison: small fix',
    author: 'carol',
    createdAt: '2026-04-14T08:00:00Z',
    mergedAt: '2026-04-14T13:30:00Z',
    additions: 12,
    deletions: 2,
    changedFiles: 1,
    reviewComments: 0,
    totalComments: 0,
    reviewers: [],
    labels: ['bug'],
  }),
  pr({
    number: 9,
    title: 'Comparison: medium feature',
    author: 'dave',
    createdAt: '2026-04-16T10:00:00Z',
    mergedAt: '2026-04-17T11:30:00Z',
    additions: 210,
    deletions: 60,
    changedFiles: 9,
    reviewComments: 5,
    totalComments: 6,
    reviewers: ['alice', 'bob'],
    labels: ['feature'],
  }),
  pr({
    number: 10,
    title: 'Comparison: tricky title, has "quotes" and, commas',
    author: 'alice',
    createdAt: '2026-04-18T07:00:00Z',
    mergedAt: '2026-04-18T15:00:00Z',
    additions: 95,
    deletions: 30,
    changedFiles: 5,
    reviewComments: 3,
    totalComments: 4,
    reviewers: ['carol'],
    labels: ['feature', 'a11y'],
  }),
  pr({
    number: 11,
    title: 'Comparison: another small bugfix',
    author: 'bob',
    createdAt: '2026-04-20T08:30:00Z',
    mergedAt: '2026-04-20T14:30:00Z',
    additions: 22,
    deletions: 5,
    changedFiles: 2,
    reviewComments: 2,
    totalComments: 2,
    reviewers: ['alice'],
    labels: ['bug'],
  }),
  pr({
    number: 12,
    title: 'Comparison: quick docs',
    author: 'carol',
    createdAt: '2026-04-22T11:00:00Z',
    mergedAt: '2026-04-22T12:00:00Z',
    additions: 6,
    deletions: 0,
    changedFiles: 1,
    reviewComments: 0,
    totalComments: 0,
    reviewers: [],
    labels: ['docs'],
  }),
];
